// Auto-generated vocabulary questions (200 total, English options format)
// Generated by scripts/generate-vocab.mjs
import { Question } from '../types';

export const generatedQuestions: Question[] = [
  {
    id: 'vocab_gen_001',
    type: 'vocabulary',
    prompt: `选择与「纪念，庆祝」对应的英文单词：`,
    options: ["commence","corrode","curb","commemorate"],
    answer: 3,
    explanation: `commemorate 意为「纪念，庆祝」。`,
    sourceEvent: '对线补兵',
    difficulty: 3
  },
  {
    id: 'vocab_gen_002',
    type: 'vocabulary',
    prompt: `选择与「能力，胜任」对应的英文单词：`,
    options: ["crack","competence","appetite","bounce"],
    answer: 1,
    explanation: `competence 意为「能力，胜任」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_003',
    type: 'vocabulary',
    prompt: `选择与「压碎，压碎」对应的英文单词：`,
    options: ["contemporary","citizen","compulsory","crush"],
    answer: 3,
    explanation: `crush 意为「压碎，压碎」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_004',
    type: 'vocabulary',
    prompt: `选择与「裂缝，破裂」对应的英文单词：`,
    options: ["cashier","crack","certificate","bureau"],
    answer: 1,
    explanation: `crack 意为「裂缝，破裂」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_005',
    type: 'vocabulary',
    prompt: `选择与「慈善，施舍」对应的英文单词：`,
    options: ["conversely","aviation","blunder","charity"],
    answer: 3,
    explanation: `charity 意为「慈善，施舍」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_006',
    type: 'vocabulary',
    prompt: `选择与「循环，流通」对应的英文单词：`,
    options: ["custody","charter","circulate","altitude"],
    answer: 2,
    explanation: `circulate 意为「循环，流通」。`,
    sourceEvent: '1v1单杀',
    difficulty: 2
  },
  {
    id: 'vocab_gen_007',
    type: 'vocabulary',
    prompt: `选择与「繁荣，激增」对应的英文单词：`,
    options: ["chase","boom","colonial","coverage"],
    answer: 1,
    explanation: `boom 意为「繁荣，激增」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_008',
    type: 'vocabulary',
    prompt: `选择与「使自动化」对应的英文单词：`,
    options: ["currency","bother","altitude","automate"],
    answer: 3,
    explanation: `automate 意为「使自动化」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_009',
    type: 'vocabulary',
    prompt: `选择与「体积，大批」对应的英文单词：`,
    options: ["crush","cabinet","bulk","brutal"],
    answer: 2,
    explanation: `bulk 意为「体积，大批」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_010',
    type: 'vocabulary',
    prompt: `选择与「抑制，控制」对应的英文单词：`,
    options: ["biological","curb","contemporary","brief"],
    answer: 1,
    explanation: `curb 意为「抑制，控制」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_011',
    type: 'vocabulary',
    prompt: `选择与「公民的，文明的」对应的英文单词：`,
    options: ["concise","alternative","articulate","civil"],
    answer: 3,
    explanation: `civil 意为「公民的，文明的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 3
  },
  {
    id: 'vocab_gen_012',
    type: 'vocabulary',
    prompt: `选择与「竞争，主张」对应的英文单词：`,
    options: ["childhood","apparatus","contend","bud"],
    answer: 2,
    explanation: `contend 意为「竞争，主张」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_013',
    type: 'vocabulary',
    prompt: `选择与「砍，剁碎」对应的英文单词：`,
    options: ["applaud","bucket","chop","broaden"],
    answer: 2,
    explanation: `chop 意为「砍，剁碎」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_014',
    type: 'vocabulary',
    prompt: `选择与「走廊，通道」对应的英文单词：`,
    options: ["bureau","corridor","banner","classic"],
    answer: 1,
    explanation: `corridor 意为「走廊，通道」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_015',
    type: 'vocabulary',
    prompt: `选择与「编译，汇编」对应的英文单词：`,
    options: ["character","compile","confer","coincide"],
    answer: 1,
    explanation: `compile 意为「编译，汇编」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_016',
    type: 'vocabulary',
    prompt: `选择与「肤色，局面」对应的英文单词：`,
    options: ["correspondence","custody","complexion","calorie"],
    answer: 2,
    explanation: `complexion 意为「肤色，局面」。`,
    sourceEvent: '对线补兵',
    difficulty: 2
  },
  {
    id: 'vocab_gen_017',
    type: 'vocabulary',
    prompt: `选择与「候选人，应试者」对应的英文单词：`,
    options: ["assault","conscientious","biological","candidate"],
    answer: 3,
    explanation: `candidate 意为「候选人，应试者」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_018',
    type: 'vocabulary',
    prompt: `选择与「批判的，关键的」对应的英文单词：`,
    options: ["compulsory","critical","commodity","concise"],
    answer: 1,
    explanation: `critical 意为「批判的，关键的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_019',
    type: 'vocabulary',
    prompt: `选择与「气泡，泡沫」对应的英文单词：`,
    options: ["collaborate","conquer","bubble","counterpart"],
    answer: 2,
    explanation: `bubble 意为「气泡，泡沫」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_020',
    type: 'vocabulary',
    prompt: `选择与「关系，方位」对应的英文单词：`,
    options: ["bubble","congress","craft","bearing"],
    answer: 3,
    explanation: `bearing 意为「关系，方位」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_021',
    type: 'vocabulary',
    prompt: `选择与「剪辑，夹子」对应的英文单词：`,
    options: ["cluster","clip","complement","condense"],
    answer: 1,
    explanation: `clip 意为「剪辑，夹子」。`,
    sourceEvent: '1v1单杀',
    difficulty: 3
  },
  {
    id: 'vocab_gen_022',
    type: 'vocabulary',
    prompt: `选择与「腐蚀，侵蚀」对应的英文单词：`,
    options: ["arithmetic","contradict","corrode","catalog"],
    answer: 2,
    explanation: `corrode 意为「腐蚀，侵蚀」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_023',
    type: 'vocabulary',
    prompt: `选择与「集体的，共同的」对应的英文单词：`,
    options: ["collective","arouse","crisis","costume"],
    answer: 0,
    explanation: `collective 意为「集体的，共同的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_024',
    type: 'vocabulary',
    prompt: `选择与「约束，限制」对应的英文单词：`,
    options: ["banner","constrain","compatible","bureau"],
    answer: 1,
    explanation: `constrain 意为「约束，限制」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_025',
    type: 'vocabulary',
    prompt: `选择与「日历，日程表」对应的英文单词：`,
    options: ["calendar","administer","commission","amaze"],
    answer: 0,
    explanation: `calendar 意为「日历，日程表」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_026',
    type: 'vocabulary',
    prompt: `选择与「魅力，吸引力」对应的英文单词：`,
    options: ["bounce","charm","attribute","bulk"],
    answer: 1,
    explanation: `charm 意为「魅力，吸引力」。`,
    sourceEvent: '敌方消耗',
    difficulty: 2
  },
  {
    id: 'vocab_gen_027',
    type: 'vocabulary',
    prompt: `选择与「公司的，法人的」对应的英文单词：`,
    options: ["continent","corporate","corrode","bound"],
    answer: 1,
    explanation: `corporate 意为「公司的，法人的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_028',
    type: 'vocabulary',
    prompt: `选择与「公民，市民」对应的英文单词：`,
    options: ["compress","citizen","concise","cruise"],
    answer: 1,
    explanation: `citizen 意为「公民，市民」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_029',
    type: 'vocabulary',
    prompt: `选择与「授予，商议」对应的英文单词：`,
    options: ["ascend","confer","cognitive","cradle"],
    answer: 1,
    explanation: `confer 意为「授予，商议」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_030',
    type: 'vocabulary',
    prompt: `选择与「组成，创作」对应的英文单词：`,
    options: ["compose","convenience","conjunction","climate"],
    answer: 0,
    explanation: `compose 意为「组成，创作」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_031',
    type: 'vocabulary',
    prompt: `选择与「清晰表达，善于表达的」对应的英文单词：`,
    options: ["cycle","altitude","articulate","cliff"],
    answer: 2,
    explanation: `articulate 意为「清晰表达，善于表达的」。`,
    sourceEvent: '对线补兵',
    difficulty: 3
  },
  {
    id: 'vocab_gen_032',
    type: 'vocabulary',
    prompt: `选择与「集群，聚集」对应的英文单词：`,
    options: ["arbitrary","allocate","cluster","ascend"],
    answer: 2,
    explanation: `cluster 意为「集群，聚集」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_033',
    type: 'vocabulary',
    prompt: `选择与「房间，室」对应的英文单词：`,
    options: ["coordinate","aggravate","articulate","chamber"],
    answer: 3,
    explanation: `chamber 意为「房间，室」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_034',
    type: 'vocabulary',
    prompt: `选择与「出席，出勤」对应的英文单词：`,
    options: ["attendance","broaden","bulletin","consolidate"],
    answer: 0,
    explanation: `attendance 意为「出席，出勤」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_035',
    type: 'vocabulary',
    prompt: `选择与「客户，委托人」对应的英文单词：`,
    options: ["bounce","arithmetic","brutal","client"],
    answer: 3,
    explanation: `client 意为「客户，委托人」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_036',
    type: 'vocabulary',
    prompt: `选择与「类别，种类」对应的英文单词：`,
    options: ["category","bounce","bubble","crown"],
    answer: 0,
    explanation: `category 意为「类别，种类」。`,
    sourceEvent: '1v1单杀',
    difficulty: 2
  },
  {
    id: 'vocab_gen_037',
    type: 'vocabulary',
    prompt: `选择与「良心，良知」对应的英文单词：`,
    options: ["conscience","bulletin","correspondence","climate"],
    answer: 0,
    explanation: `conscience 意为「良心，良知」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_038',
    type: 'vocabulary',
    prompt: `选择与「殖民的，殖民地的」对应的英文单词：`,
    options: ["bewilder","colonial","circular","consult"],
    answer: 1,
    explanation: `colonial 意为「殖民的，殖民地的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_039',
    type: 'vocabulary',
    prompt: `选择与「束，串，群」对应的英文单词：`,
    options: ["bunch","compliance","compel","cape"],
    answer: 0,
    explanation: `bunch 意为「束，串，群」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_040',
    type: 'vocabulary',
    prompt: `选择与「校园，校区」对应的英文单词：`,
    options: ["cradle","campus","cherish","bud"],
    answer: 1,
    explanation: `campus 意为「校园，校区」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_041',
    type: 'vocabulary',
    prompt: `选择与「合作，协作」对应的英文单词：`,
    options: ["collaborate","credible","craft","altitude"],
    answer: 0,
    explanation: `collaborate 意为「合作，协作」。`,
    sourceEvent: '敌方消耗',
    difficulty: 3
  },
  {
    id: 'vocab_gen_042',
    type: 'vocabulary',
    prompt: `选择与「内阁，橱柜」对应的英文单词：`,
    options: ["cabinet","complexion","circuit","conjunction"],
    answer: 0,
    explanation: `cabinet 意为「内阁，橱柜」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_043',
    type: 'vocabulary',
    prompt: `选择与「紧凑的，简洁的」对应的英文单词：`,
    options: ["brink","compact","academy","aviation"],
    answer: 1,
    explanation: `compact 意为「紧凑的，简洁的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_044',
    type: 'vocabulary',
    prompt: `选择与「经典的，典型的」对应的英文单词：`,
    options: ["conception","classic","crisis","corporate"],
    answer: 1,
    explanation: `classic 意为「经典的，典型的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_045',
    type: 'vocabulary',
    prompt: `选择与「奇异的，怪诞的」对应的英文单词：`,
    options: ["compliance","bound","cherish","bizarre"],
    answer: 3,
    explanation: `bizarre 意为「奇异的，怪诞的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_046',
    type: 'vocabulary',
    prompt: `选择与「矛盾，反驳」对应的英文单词：`,
    options: ["comply","colleague","congress","contradict"],
    answer: 3,
    explanation: `contradict 意为「矛盾，反驳」。`,
    sourceEvent: '对线补兵',
    difficulty: 2
  },
  {
    id: 'vocab_gen_047',
    type: 'vocabulary',
    prompt: `选择与「青铜，古铜色」对应的英文单词：`,
    options: ["bronze","curriculum","choke","commerce"],
    answer: 0,
    explanation: `bronze 意为「青铜，古铜色」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_048',
    type: 'vocabulary',
    prompt: `选择与「传达，运输」对应的英文单词：`,
    options: ["convey","cease","bonus","bronze"],
    answer: 0,
    explanation: `convey 意为「传达，运输」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_049',
    type: 'vocabulary',
    prompt: `选择与「碰撞，坠毁」对应的英文单词：`,
    options: ["compulsory","constrain","crash","beforehand"],
    answer: 2,
    explanation: `crash 意为「碰撞，坠毁」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_050',
    type: 'vocabulary',
    prompt: `选择与「定罪，证明…有罪」对应的英文单词：`,
    options: ["convict","congress","benevolent","claim"],
    answer: 0,
    explanation: `convict 意为「定罪，证明…有罪」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_051',
    type: 'vocabulary',
    prompt: `选择与「协调，坐标」对应的英文单词：`,
    options: ["conceal","combat","crisis","coordinate"],
    answer: 3,
    explanation: `coordinate 意为「协调，坐标」。`,
    sourceEvent: '1v1单杀',
    difficulty: 3
  },
  {
    id: 'vocab_gen_052',
    type: 'vocabulary',
    prompt: `选择与「获得，习得」对应的英文单词：`,
    options: ["cognitive","convert","allege","acquisition"],
    answer: 3,
    explanation: `acquisition 意为「获得，习得」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_053',
    type: 'vocabulary',
    prompt: `选择与「诅咒，咒骂」对应的英文单词：`,
    options: ["curse","courtesy","boom","compress"],
    answer: 0,
    explanation: `curse 意为「诅咒，咒骂」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_054',
    type: 'vocabulary',
    prompt: `选择与「公共的，社区的」对应的英文单词：`,
    options: ["communal","commission","circuit","conception"],
    answer: 0,
    explanation: `communal 意为「公共的，社区的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_055',
    type: 'vocabulary',
    prompt: `选择与「碰撞，冲突」对应的英文单词：`,
    options: ["collision","confrontation","courtesy","aggravate"],
    answer: 0,
    explanation: `collision 意为「碰撞，冲突」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_056',
    type: 'vocabulary',
    prompt: `选择与「大街，途径」对应的英文单词：`,
    options: ["brand","avenue","alternative","conjunction"],
    answer: 1,
    explanation: `avenue 意为「大街，途径」。`,
    sourceEvent: '敌方消耗',
    difficulty: 2
  },
  {
    id: 'vocab_gen_057',
    type: 'vocabulary',
    prompt: `选择与「愤世嫉俗的」对应的英文单词：`,
    options: ["compulsory","cynical","concise","colleague"],
    answer: 1,
    explanation: `cynical 意为「愤世嫉俗的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_058',
    type: 'vocabulary',
    prompt: `选择与「认知的，认识的」对应的英文单词：`,
    options: ["cargo","cognitive","attribute","chase"],
    answer: 1,
    explanation: `cognitive 意为「认知的，认识的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_059',
    type: 'vocabulary',
    prompt: `选择与「目录，编目」对应的英文单词：`,
    options: ["clarify","climate","catalog","contempt"],
    answer: 2,
    explanation: `catalog 意为「目录，编目」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_060',
    type: 'vocabulary',
    prompt: `选择与「评价，估价」对应的英文单词：`,
    options: ["appraisal","comprehension","attribute","copyright"],
    answer: 0,
    explanation: `appraisal 意为「评价，估价」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_061',
    type: 'vocabulary',
    prompt: `选择与「征服，克服」对应的英文单词：`,
    options: ["conquer","critical","contradict","corridor"],
    answer: 0,
    explanation: `conquer 意为「征服，克服」。`,
    sourceEvent: '对线补兵',
    difficulty: 3
  },
  {
    id: 'vocab_gen_062',
    type: 'vocabulary',
    prompt: `选择与「收银员，出纳员」对应的英文单词：`,
    options: ["candidate","cautious","cashier","bribe"],
    answer: 2,
    explanation: `cashier 意为「收银员，出纳员」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_063',
    type: 'vocabulary',
    prompt: `选择与「横幅，旗帜」对应的英文单词：`,
    options: ["conquer","apparatus","banner","crude"],
    answer: 2,
    explanation: `banner 意为「横幅，旗帜」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_064',
    type: 'vocabulary',
    prompt: `选择与「蓝图，计划」对应的英文单词：`,
    options: ["brief","benevolent","converge","blueprint"],
    answer: 3,
    explanation: `blueprint 意为「蓝图，计划」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_065',
    type: 'vocabulary',
    prompt: `选择与「化合物，复合的」对应的英文单词：`,
    options: ["breach","compound","conquer","contend"],
    answer: 1,
    explanation: `compound 意为「化合物，复合的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_066',
    type: 'vocabulary',
    prompt: `选择与「使惊奇，使惊愕」对应的英文单词：`,
    options: ["brief","concise","amaze","commonplace"],
    answer: 2,
    explanation: `amaze 意为「使惊奇，使惊愕」。`,
    sourceEvent: '1v1单杀',
    difficulty: 2
  },
  {
    id: 'vocab_gen_067',
    type: 'vocabulary',
    prompt: `选择与「服从，遵守」对应的英文单词：`,
    options: ["compliance","council","convert","copyright"],
    answer: 0,
    explanation: `compliance 意为「服从，遵守」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_068',
    type: 'vocabulary',
    prompt: `选择与「标准，准则」对应的英文单词：`,
    options: ["coordinate","agenda","conceive","criterion"],
    answer: 3,
    explanation: `criterion 意为「标准，准则」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_069',
    type: 'vocabulary',
    prompt: `选择与「监护，拘留」对应的英文单词：`,
    options: ["cultivate","congress","articulate","custody"],
    answer: 3,
    explanation: `custody 意为「监护，拘留」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_070',
    type: 'vocabulary',
    prompt: `选择与「在…下方」对应的英文单词：`,
    options: ["breach","cashier","beneath","bizarre"],
    answer: 2,
    explanation: `beneath 意为「在…下方」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_071',
    type: 'vocabulary',
    prompt: `选择与「条款，从句」对应的英文单词：`,
    options: ["continent","capable","bureau","clause"],
    answer: 3,
    explanation: `clause 意为「条款，从句」。`,
    sourceEvent: '敌方消耗',
    difficulty: 3
  },
  {
    id: 'vocab_gen_072',
    type: 'vocabulary',
    prompt: `选择与「商品，货物」对应的英文单词：`,
    options: ["commodity","crystal","clarify","articulate"],
    answer: 0,
    explanation: `commodity 意为「商品，货物」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_073',
    type: 'vocabulary',
    prompt: `选择与「符合，遵守」对应的英文单词：`,
    options: ["bureau","conform","cycle","coarse"],
    answer: 1,
    explanation: `conform 意为「符合，遵守」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_074',
    type: 'vocabulary',
    prompt: `选择与「兼容的，相容的」对应的英文单词：`,
    options: ["astronomy","altitude","compatible","corrupt"],
    answer: 2,
    explanation: `compatible 意为「兼容的，相容的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_075',
    type: 'vocabulary',
    prompt: `选择与「商业，贸易」对应的英文单词：`,
    options: ["compel","commerce","competence","bud"],
    answer: 1,
    explanation: `commerce 意为「商业，贸易」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_076',
    type: 'vocabulary',
    prompt: `选择与「边缘」对应的英文单词：`,
    options: ["brutal","consult","brink","biological"],
    answer: 2,
    explanation: `brink 意为「边缘」。`,
    sourceEvent: '对线补兵',
    difficulty: 2
  },
  {
    id: 'vocab_gen_077',
    type: 'vocabulary',
    prompt: `选择与「学院，研究院」对应的英文单词：`,
    options: ["cargo","cliff","costume","academy"],
    answer: 3,
    explanation: `academy 意为「学院，研究院」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_078',
    type: 'vocabulary',
    prompt: `选择与「教练，长途汽车」对应的英文单词：`,
    options: ["coach","contradict","conservation","breed"],
    answer: 0,
    explanation: `coach 意为「教练，长途汽车」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_079',
    type: 'vocabulary',
    prompt: `选择与「追逐，追赶」对应的英文单词：`,
    options: ["converge","clash","chase","compulsory"],
    answer: 2,
    explanation: `chase 意为「追逐，追赶」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_080',
    type: 'vocabulary',
    prompt: `选择与「澄清，阐明」对应的英文单词：`,
    options: ["curriculum","craft","confine","clarify"],
    answer: 3,
    explanation: `clarify 意为「澄清，阐明」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_081',
    type: 'vocabulary',
    prompt: `选择与「粗糙的，天然的」对应的英文单词：`,
    options: ["articulate","crude","coincide","concede"],
    answer: 1,
    explanation: `crude 意为「粗糙的，天然的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 3
  },
  {
    id: 'vocab_gen_082',
    type: 'vocabulary',
    prompt: `选择与「立方的，立方体的」对应的英文单词：`,
    options: ["cubic","costume","bizarre","attendance"],
    answer: 0,
    explanation: `cubic 意为「立方的，立方体的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_083',
    type: 'vocabulary',
    prompt: `选择与「相关，关联」对应的英文单词：`,
    options: ["correlate","conquer","classic","conviction"],
    answer: 0,
    explanation: `correlate 意为「相关，关联」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_084',
    type: 'vocabulary',
    prompt: `选择与「开始，着手」对应的英文单词：`,
    options: ["chase","aspiration","architecture","commence"],
    answer: 3,
    explanation: `commence 意为「开始，着手」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_085',
    type: 'vocabulary',
    prompt: `选择与「体贴的，考虑周到的」对应的英文单词：`,
    options: ["appraisal","copyright","considerate","cluster"],
    answer: 2,
    explanation: `considerate 意为「体贴的，考虑周到的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_086',
    type: 'vocabulary',
    prompt: `选择与「贿赂，行贿」对应的英文单词：`,
    options: ["conceive","anonymous","bribe","betray"],
    answer: 2,
    explanation: `bribe 意为「贿赂，行贿」。`,
    sourceEvent: '敌方消耗',
    difficulty: 2
  },
  {
    id: 'vocab_gen_087',
    type: 'vocabulary',
    prompt: `选择与「声称，断言」对应的英文单词：`,
    options: ["brutal","allege","contemporary","crack"],
    answer: 1,
    explanation: `allege 意为「声称，断言」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_088',
    type: 'vocabulary',
    prompt: `选择与「一致的，始终如一的」对应的英文单词：`,
    options: ["consistent","comprehension","copyright","charity"],
    answer: 0,
    explanation: `consistent 意为「一致的，始终如一的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_089',
    type: 'vocabulary',
    prompt: `选择与「证书，证明」对应的英文单词：`,
    options: ["considerate","character","certificate","collaborate"],
    answer: 2,
    explanation: `certificate 意为「证书，证明」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_090',
    type: 'vocabulary',
    prompt: `选择与「热情的，真诚的」对应的英文单词：`,
    options: ["aviation","bureau","cordial","considerate"],
    answer: 2,
    explanation: `cordial 意为「热情的，真诚的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_091',
    type: 'vocabulary',
    prompt: `选择与「摇篮，发源地」对应的英文单词：`,
    options: ["cradle","census","cling","charm"],
    answer: 0,
    explanation: `cradle 意为「摇篮，发源地」。`,
    sourceEvent: '对线补兵',
    difficulty: 3
  },
  {
    id: 'vocab_gen_092',
    type: 'vocabulary',
    prompt: `选择与「界限，限制」对应的英文单词：`,
    options: ["cease","cruise","administer","bound"],
    answer: 3,
    explanation: `bound 意为「界限，限制」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_093',
    type: 'vocabulary',
    prompt: `选择与「国会，代表大会」对应的英文单词：`,
    options: ["comprehension","congress","curb","cape"],
    answer: 1,
    explanation: `congress 意为「国会，代表大会」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_094',
    type: 'vocabulary',
    prompt: `选择与「算术，计算」对应的英文单词：`,
    options: ["criterion","cubic","arithmetic","custody"],
    answer: 2,
    explanation: `arithmetic 意为「算术，计算」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_095',
    type: 'vocabulary',
    prompt: `选择与「鼓掌，称赞」对应的英文单词：`,
    options: ["compliance","applaud","corridor","bonus"],
    answer: 1,
    explanation: `applaud 意为「鼓掌，称赞」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_096',
    type: 'vocabulary',
    prompt: `选择与「赞美，恭维」对应的英文单词：`,
    options: ["compliment","craft","cliff","cautious"],
    answer: 0,
    explanation: `compliment 意为「赞美，恭维」。`,
    sourceEvent: '1v1单杀',
    difficulty: 2
  },
  {
    id: 'vocab_gen_097',
    type: 'vocabulary',
    prompt: `选择与「性格，角色」对应的英文单词：`,
    options: ["contempt","considerate","crisis","character"],
    answer: 3,
    explanation: `character 意为「性格，角色」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_098',
    type: 'vocabulary',
    prompt: `选择与「沉思，冥想」对应的英文单词：`,
    options: ["constitute","beforehand","corrode","contemplate"],
    answer: 3,
    explanation: `contemplate 意为「沉思，冥想」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_099',
    type: 'vocabulary',
    prompt: `选择与「汇聚，集中」对应的英文单词：`,
    options: ["brief","converge","contemporary","breed"],
    answer: 1,
    explanation: `converge 意为「汇聚，集中」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_100',
    type: 'vocabulary',
    prompt: `选择与「背叛，泄露」对应的英文单词：`,
    options: ["altitude","cruise","betray","constrain"],
    answer: 2,
    explanation: `betray 意为「背叛，泄露」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_101',
    type: 'vocabulary',
    prompt: `选择与「引用，引证」对应的英文单词：`,
    options: ["brutal","cite","bulk","applicable"],
    answer: 1,
    explanation: `cite 意为「引用，引证」。`,
    sourceEvent: '敌方消耗',
    difficulty: 3
  },
  {
    id: 'vocab_gen_102',
    type: 'vocabulary',
    prompt: `选择与「好奇心，求知欲」对应的英文单词：`,
    options: ["conform","comprehension","bearing","curiosity"],
    answer: 3,
    explanation: `curiosity 意为「好奇心，求知欲」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_103',
    type: 'vocabulary',
    prompt: `选择与「加重，恶化」对应的英文单词：`,
    options: ["compensate","controversial","aggravate","colleague"],
    answer: 2,
    explanation: `aggravate 意为「加重，恶化」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_104',
    type: 'vocabulary',
    prompt: `选择与「悬崖，峭壁」对应的英文单词：`,
    options: ["bearing","bucket","cliff","commerce"],
    answer: 2,
    explanation: `cliff 意为「悬崖，峭壁」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_105',
    type: 'vocabulary',
    prompt: `选择与「渴望，志向」对应的英文单词：`,
    options: ["brink","confine","aspiration","chip"],
    answer: 2,
    explanation: `aspiration 意为「渴望，志向」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_106',
    type: 'vocabulary',
    prompt: `选择与「简短的，摘要」对应的英文单词：`,
    options: ["alternative","brief","charity","critical"],
    answer: 1,
    explanation: `brief 意为「简短的，摘要」。`,
    sourceEvent: '对线补兵',
    difficulty: 2
  },
  {
    id: 'vocab_gen_107',
    type: 'vocabulary',
    prompt: `选择与「咨询，查阅」对应的英文单词：`,
    options: ["coarse","consult","clarify","applaud"],
    answer: 1,
    explanation: `consult 意为「咨询，查阅」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_108',
    type: 'vocabulary',
    prompt: `选择与「海角，披肩」对应的英文单词：`,
    options: ["astronomy","allege","correspondence","cape"],
    answer: 3,
    explanation: `cape 意为「海角，披肩」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_109',
    type: 'vocabulary',
    prompt: `选择与「瘀伤，擦伤」对应的英文单词：`,
    options: ["bruise","commence","agenda","boom"],
    answer: 0,
    explanation: `bruise 意为「瘀伤，擦伤」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_110',
    type: 'vocabulary',
    prompt: `选择与「大错，犯错误」对应的英文单词：`,
    options: ["blunder","compulsory","cite","blueprint"],
    answer: 0,
    explanation: `blunder 意为「大错，犯错误」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_111',
    type: 'vocabulary',
    prompt: `选择与「对抗，冲突」对应的英文单词：`,
    options: ["arouse","childhood","confrontation","bewilder"],
    answer: 2,
    explanation: `confrontation 意为「对抗，冲突」。`,
    sourceEvent: '1v1单杀',
    difficulty: 3
  },
  {
    id: 'vocab_gen_112',
    type: 'vocabulary',
    prompt: `选择与「学士，单身汉」对应的英文单词：`,
    options: ["bachelor","critical","conversely","crisis"],
    answer: 0,
    explanation: `bachelor 意为「学士，单身汉」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_113',
    type: 'vocabulary',
    prompt: `选择与「上升，攀登」对应的英文单词：`,
    options: ["bunch","agenda","ascend","contend"],
    answer: 2,
    explanation: `ascend 意为「上升，攀登」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_114',
    type: 'vocabulary',
    prompt: `选择与「同意，允许」对应的英文单词：`,
    options: ["council","cabinet","curve","consent"],
    answer: 3,
    explanation: `consent 意为「同意，允许」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_115',
    type: 'vocabulary',
    prompt: `选择与「卡路里」对应的英文单词：`,
    options: ["calorie","cabinet","brief","accumulate"],
    answer: 0,
    explanation: `calorie 意为「卡路里」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_116',
    type: 'vocabulary',
    prompt: `选择与「王冠，皇冠」对应的英文单词：`,
    options: ["compliance","bulk","cubic","crown"],
    answer: 3,
    explanation: `crown 意为「王冠，皇冠」。`,
    sourceEvent: '敌方消耗',
    difficulty: 2
  },
  {
    id: 'vocab_gen_117',
    type: 'vocabulary',
    prompt: `选择与「遵从，服从」对应的英文单词：`,
    options: ["bizarre","attribute","arithmetic","comply"],
    answer: 3,
    explanation: `comply 意为「遵从，服从」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_118',
    type: 'vocabulary',
    prompt: `选择与「积累，积聚」对应的英文单词：`,
    options: ["auxiliary","acquisition","accumulate","capable"],
    answer: 2,
    explanation: `accumulate 意为「积累，积聚」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_119',
    type: 'vocabulary',
    prompt: `选择与「品牌，商标」对应的英文单词：`,
    options: ["contradict","brutal","bizarre","brand"],
    answer: 3,
    explanation: `brand 意为「品牌，商标」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_120',
    type: 'vocabulary',
    prompt: `选择与「巡航，游轮」对应的英文单词：`,
    options: ["cruise","barren","abstract","contend"],
    answer: 0,
    explanation: `cruise 意为「巡航，游轮」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_121',
    type: 'vocabulary',
    prompt: `选择与「工艺，手艺」对应的英文单词：`,
    options: ["craft","adolescent","curiosity","convert"],
    answer: 0,
    explanation: `craft 意为「工艺，手艺」。`,
    sourceEvent: '对线补兵',
    difficulty: 3
  },
  {
    id: 'vocab_gen_122',
    type: 'vocabulary',
    prompt: `选择与「连贯的，一致的」对应的英文单词：`,
    options: ["coherent","breed","candidate","beforehand"],
    answer: 0,
    explanation: `coherent 意为「连贯的，一致的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_123',
    type: 'vocabulary',
    prompt: `选择与「连接，结合」对应的英文单词：`,
    options: ["consecutive","brutal","charm","conjunction"],
    answer: 3,
    explanation: `conjunction 意为「连接，结合」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_124',
    type: 'vocabulary',
    prompt: `选择与「停止，终止」对应的英文单词：`,
    options: ["assault","allege","cease","calendar"],
    answer: 2,
    explanation: `cease 意为「停止，终止」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_125',
    type: 'vocabulary',
    prompt: `选择与「芽，花蕾」对应的英文单词：`,
    options: ["conventional","crude","bud","colonial"],
    answer: 2,
    explanation: `bud 意为「芽，花蕾」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_126',
    type: 'vocabulary',
    prompt: `选择与「打扰，烦恼」对应的英文单词：`,
    options: ["compose","cognitive","bother","curb"],
    answer: 2,
    explanation: `bother 意为「打扰，烦恼」。`,
    sourceEvent: '1v1单杀',
    difficulty: 2
  },
  {
    id: 'vocab_gen_127',
    type: 'vocabulary',
    prompt: `选择与「培养，耕作」对应的英文单词：`,
    options: ["cultivate","cling","conform","bloom"],
    answer: 0,
    explanation: `cultivate 意为「培养，耕作」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_128',
    type: 'vocabulary',
    prompt: `选择与「使迷惑，使困惑」对应的英文单词：`,
    options: ["bewilder","accumulate","condense","compress"],
    answer: 0,
    explanation: `bewilder 意为「使迷惑，使困惑」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_129',
    type: 'vocabulary',
    prompt: `选择与「圆形的，循环的」对应的英文单词：`,
    options: ["cautious","cargo","corrode","circular"],
    answer: 3,
    explanation: `circular 意为「圆形的，循环的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_130',
    type: 'vocabulary',
    prompt: `选择与「水桶，桶」对应的英文单词：`,
    options: ["conjunction","bucket","bud","communal"],
    answer: 1,
    explanation: `bucket 意为「水桶，桶」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_131',
    type: 'vocabulary',
    prompt: `选择与「碎片，芯片」对应的英文单词：`,
    options: ["capable","circulate","conform","chip"],
    answer: 3,
    explanation: `chip 意为「碎片，芯片」。`,
    sourceEvent: '敌方消耗',
    difficulty: 3
  },
  {
    id: 'vocab_gen_132',
    type: 'vocabulary',
    prompt: `选择与「天文学」对应的英文单词：`,
    options: ["compliment","communal","astronomy","cape"],
    answer: 2,
    explanation: `astronomy 意为「天文学」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_133',
    type: 'vocabulary',
    prompt: `选择与「评论，意见」对应的英文单词：`,
    options: ["custody","cargo","comment","certificate"],
    answer: 2,
    explanation: `comment 意为「评论，意见」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_134',
    type: 'vocabulary',
    prompt: `选择与「火焰，燃烧」对应的英文单词：`,
    options: ["constitute","arithmetic","blaze","anonymous"],
    answer: 2,
    explanation: `blaze 意为「火焰，燃烧」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_135',
    type: 'vocabulary',
    prompt: `选择与「曲线，弯曲」对应的英文单词：`,
    options: ["comprehension","cubic","curve","calorie"],
    answer: 2,
    explanation: `curve 意为「曲线，弯曲」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_136',
    type: 'vocabulary',
    prompt: `选择与「窒息，阻塞」对应的英文单词：`,
    options: ["beforehand","comprehension","cluster","choke"],
    answer: 3,
    explanation: `choke 意为「窒息，阻塞」。`,
    sourceEvent: '对线补兵',
    difficulty: 2
  },
  {
    id: 'vocab_gen_137',
    type: 'vocabulary',
    prompt: `选择与「突破，重大发现」对应的英文单词：`,
    options: ["breakthrough","assault","curb","crown"],
    answer: 0,
    explanation: `breakthrough 意为「突破，重大发现」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_138',
    type: 'vocabulary',
    prompt: `选择与「冲突，碰撞」对应的英文单词：`,
    options: ["clash","competence","automate","convenience"],
    answer: 0,
    explanation: `clash 意为「冲突，碰撞」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_139',
    type: 'vocabulary',
    prompt: `选择与「有争议的」对应的英文单词：`,
    options: ["compile","controversial","acquisition","condense"],
    answer: 1,
    explanation: `controversial 意为「有争议的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_140',
    type: 'vocabulary',
    prompt: `选择与「可比较的，类似的」对应的英文单词：`,
    options: ["comparable","bias","courtesy","compile"],
    answer: 0,
    explanation: `comparable 意为「可比较的，类似的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_141',
    type: 'vocabulary',
    prompt: `选择与「强迫，迫使」对应的英文单词：`,
    options: ["conspicuous","biological","consecutive","compel"],
    answer: 3,
    explanation: `compel 意为「强迫，迫使」。`,
    sourceEvent: '1v1单杀',
    difficulty: 3
  },
  {
    id: 'vocab_gen_142',
    type: 'vocabulary',
    prompt: `选择与「声称，要求」对应的英文单词：`,
    options: ["curriculum","courtesy","brink","claim"],
    answer: 3,
    explanation: `claim 意为「声称，要求」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_143',
    type: 'vocabulary',
    prompt: `选择与「分配，拨出」对应的英文单词：`,
    options: ["aspiration","allocate","corrupt","clause"],
    answer: 1,
    explanation: `allocate 意为「分配，拨出」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_144',
    type: 'vocabulary',
    prompt: `选择与「战斗，与…战斗」对应的英文单词：`,
    options: ["colonial","banner","combat","blueprint"],
    answer: 2,
    explanation: `combat 意为「战斗，与…战斗」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_145',
    type: 'vocabulary',
    prompt: `选择与「唤醒，激起」对应的英文单词：`,
    options: ["curriculum","competence","crude","arouse"],
    answer: 3,
    explanation: `arouse 意为「唤醒，激起」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_146',
    type: 'vocabulary',
    prompt: `选择与「同时发生，巧合」对应的英文单词：`,
    options: ["cushion","coincide","colonial","amaze"],
    answer: 1,
    explanation: `coincide 意为「同时发生，巧合」。`,
    sourceEvent: '敌方消耗',
    difficulty: 2
  },
  {
    id: 'vocab_gen_147',
    type: 'vocabulary',
    prompt: `选择与「对应的人或物」对应的英文单词：`,
    options: ["bureau","bearing","communal","counterpart"],
    answer: 3,
    explanation: `counterpart 意为「对应的人或物」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_148',
    type: 'vocabulary',
    prompt: `选择与「主要的，首领」对应的英文单词：`,
    options: ["chief","compatible","bonus","commodity"],
    answer: 0,
    explanation: `chief 意为「主要的，首领」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_149',
    type: 'vocabulary',
    prompt: `选择与「航空，飞行」对应的英文单词：`,
    options: ["assault","conjunction","aviation","curiosity"],
    answer: 2,
    explanation: `aviation 意为「航空，飞行」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_150',
    type: 'vocabulary',
    prompt: `选择与「繁殖，饲养」对应的英文单词：`,
    options: ["compulsory","curiosity","craft","breed"],
    answer: 3,
    explanation: `breed 意为「繁殖，饲养」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_151',
    type: 'vocabulary',
    prompt: `选择与「同情，怜悯」对应的英文单词：`,
    options: ["appraisal","complexion","clinic","compassion"],
    answer: 3,
    explanation: `compassion 意为「同情，怜悯」。`,
    sourceEvent: '对线补兵',
    difficulty: 3
  },
  {
    id: 'vocab_gen_152',
    type: 'vocabulary',
    prompt: `选择与「谨慎的，小心的」对应的英文单词：`,
    options: ["comply","cautious","comprise","bulletin"],
    answer: 1,
    explanation: `cautious 意为「谨慎的，小心的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_153',
    type: 'vocabulary',
    prompt: `选择与「服装，戏服」对应的英文单词：`,
    options: ["alternative","continent","costume","criterion"],
    answer: 2,
    explanation: `costume 意为「服装，戏服」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_154',
    type: 'vocabulary',
    prompt: `选择与「属性，归因于」对应的英文单词：`,
    options: ["attribute","corridor","blunder","assault"],
    answer: 0,
    explanation: `attribute 意为「属性，归因于」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_155',
    type: 'vocabulary',
    prompt: `选择与「反弹，弹跳」对应的英文单词：`,
    options: ["bulletin","compliment","bounce","comprehension"],
    answer: 2,
    explanation: `bounce 意为「反弹，弹跳」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_156',
    type: 'vocabulary',
    prompt: `选择与「通信，信件」对应的英文单词：`,
    options: ["correlate","correspondence","clause","cautious"],
    answer: 1,
    explanation: `correspondence 意为「通信，信件」。`,
    sourceEvent: '1v1单杀',
    difficulty: 2
  },
  {
    id: 'vocab_gen_157',
    type: 'vocabulary',
    prompt: `选择与「认真的，尽责的」对应的英文单词：`,
    options: ["conscientious","allege","arouse","calendar"],
    answer: 0,
    explanation: `conscientious 意为「认真的，尽责的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_158',
    type: 'vocabulary',
    prompt: `选择与「议程，日程」对应的英文单词：`,
    options: ["bulletin","chamber","consult","agenda"],
    answer: 3,
    explanation: `agenda 意为「议程，日程」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_159',
    type: 'vocabulary',
    prompt: `选择与「运河，水道」对应的英文单词：`,
    options: ["brand","canal","abstract","cubic"],
    answer: 1,
    explanation: `canal 意为「运河，水道」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_160',
    type: 'vocabulary',
    prompt: `选择与「偏见，偏差」对应的英文单词：`,
    options: ["anniversary","bewilder","council","bias"],
    answer: 3,
    explanation: `bias 意为「偏见，偏差」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_161',
    type: 'vocabulary',
    prompt: `选择与「任意的，武断的」对应的英文单词：`,
    options: ["cycle","compulsory","brand","arbitrary"],
    answer: 3,
    explanation: `arbitrary 意为「任意的，武断的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 3
  },
  {
    id: 'vocab_gen_162',
    type: 'vocabulary',
    prompt: `选择与「局，办事处」对应的英文单词：`,
    options: ["census","bureau","brutal","counterpart"],
    answer: 1,
    explanation: `bureau 意为「局，办事处」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_163',
    type: 'vocabulary',
    prompt: `选择与「组成，构成」对应的英文单词：`,
    options: ["consolidate","constitute","considerate","bounce"],
    answer: 1,
    explanation: `constitute 意为「组成，构成」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_164',
    type: 'vocabulary',
    prompt: `选择与「限制，禁闭」对应的英文单词：`,
    options: ["criterion","confine","cherish","comprise"],
    answer: 1,
    explanation: `confine 意为「限制，禁闭」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_165',
    type: 'vocabulary',
    prompt: `选择与「强制的，必修的」对应的英文单词：`,
    options: ["conquer","compulsory","apparatus","appraisal"],
    answer: 1,
    explanation: `compulsory 意为「强制的，必修的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_166',
    type: 'vocabulary',
    prompt: `选择与「保证，保险」对应的英文单词：`,
    options: ["assurance","bias","applicable","costume"],
    answer: 0,
    explanation: `assurance 意为「保证，保险」。`,
    sourceEvent: '对线补兵',
    difficulty: 2
  },
  {
    id: 'vocab_gen_167',
    type: 'vocabulary',
    prompt: `选择与「信念，定罪」对应的英文单词：`,
    options: ["conviction","compensate","cluster","consent"],
    answer: 0,
    explanation: `conviction 意为「信念，定罪」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_168',
    type: 'vocabulary',
    prompt: `选择与「高度，海拔」对应的英文单词：`,
    options: ["betray","altitude","bud","cubic"],
    answer: 1,
    explanation: `altitude 意为「高度，海拔」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_169',
    type: 'vocabulary',
    prompt: `选择与「坚持，依附」对应的英文单词：`,
    options: ["contemplate","cognitive","cling","bother"],
    answer: 2,
    explanation: `cling 意为「坚持，依附」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_170',
    type: 'vocabulary',
    prompt: `选择与「大使，使节」对应的英文单词：`,
    options: ["ambassador","consult","compulsory","confrontation"],
    answer: 0,
    explanation: `ambassador 意为「大使，使节」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_171',
    type: 'vocabulary',
    prompt: `选择与「浓缩，压缩」对应的英文单词：`,
    options: ["comet","bulletin","condense","compensate"],
    answer: 2,
    explanation: `condense 意为「浓缩，压缩」。`,
    sourceEvent: '1v1单杀',
    difficulty: 3
  },
  {
    id: 'vocab_gen_172',
    type: 'vocabulary',
    prompt: `选择与「概念，观念」对应的英文单词：`,
    options: ["conception","cuisine","council","crude"],
    answer: 0,
    explanation: `conception 意为「概念，观念」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_173',
    type: 'vocabulary',
    prompt: `选择与「烹饪，菜肴」对应的英文单词：`,
    options: ["charter","chase","cuisine","arouse"],
    answer: 2,
    explanation: `cuisine 意为「烹饪，菜肴」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_174',
    type: 'vocabulary',
    prompt: `选择与「抽象的，理论上的」对应的英文单词：`,
    options: ["amaze","commemorate","astronomy","abstract"],
    answer: 3,
    explanation: `abstract 意为「抽象的，理论上的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_175',
    type: 'vocabulary',
    prompt: `选择与「运输工具，载体」对应的英文单词：`,
    options: ["cite","curriculum","carrier","coverage"],
    answer: 2,
    explanation: `carrier 意为「运输工具，载体」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_176',
    type: 'vocabulary',
    prompt: `选择与「可信的，可靠的」对应的英文单词：`,
    options: ["chill","bachelor","credible","climate"],
    answer: 2,
    explanation: `credible 意为「可信的，可靠的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 2
  },
  {
    id: 'vocab_gen_177',
    type: 'vocabulary',
    prompt: `选择与「覆盖范围，报道」对应的英文单词：`,
    options: ["commonplace","condemn","brink","coverage"],
    answer: 3,
    explanation: `coverage 意为「覆盖范围，报道」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_178',
    type: 'vocabulary',
    prompt: `选择与「相反地」对应的英文单词：`,
    options: ["comet","conversely","cite","brief"],
    answer: 1,
    explanation: `conversely 意为「相反地」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_179',
    type: 'vocabulary',
    prompt: `选择与「谴责，判刑」对应的英文单词：`,
    options: ["bureau","cliff","condemn","agenda"],
    answer: 2,
    explanation: `condemn 意为「谴责，判刑」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_180',
    type: 'vocabulary',
    prompt: `选择与「关键的，决定性的」对应的英文单词：`,
    options: ["compliment","barren","crucial","compact"],
    answer: 2,
    explanation: `crucial 意为「关键的，决定性的」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_181',
    type: 'vocabulary',
    prompt: `选择与「建筑学，建筑风格」对应的英文单词：`,
    options: ["contemporary","cultivate","apparatus","architecture"],
    answer: 3,
    explanation: `architecture 意为「建筑学，建筑风格」。`,
    sourceEvent: '对线补兵',
    difficulty: 3
  },
  {
    id: 'vocab_gen_182',
    type: 'vocabulary',
    prompt: `选择与「残忍的，野蛮的」对应的英文单词：`,
    options: ["curb","brutal","academy","compile"],
    answer: 1,
    explanation: `brutal 意为「残忍的，野蛮的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_183',
    type: 'vocabulary',
    prompt: `选择与「轻视，蔑视」对应的英文单词：`,
    options: ["curse","condense","contempt","clarify"],
    answer: 2,
    explanation: `contempt 意为「轻视，蔑视」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_184',
    type: 'vocabulary',
    prompt: `选择与「理解，理解力」对应的英文单词：`,
    options: ["compatible","comprehension","controversial","conceive"],
    answer: 1,
    explanation: `comprehension 意为「理解，理解力」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_185',
    type: 'vocabulary',
    prompt: `选择与「货物，船货」对应的英文单词：`,
    options: ["cargo","acquisition","barren","bound"],
    answer: 0,
    explanation: `cargo 意为「货物，船货」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_186',
    type: 'vocabulary',
    prompt: `选择与「水晶，晶体」对应的英文单词：`,
    options: ["conservation","catalog","crystal","climate"],
    answer: 2,
    explanation: `crystal 意为「水晶，晶体」。`,
    sourceEvent: '1v1单杀',
    difficulty: 2
  },
  {
    id: 'vocab_gen_187',
    type: 'vocabulary',
    prompt: `选择与「攻击，袭击」对应的英文单词：`,
    options: ["beforehand","arouse","acquisition","assault"],
    answer: 3,
    explanation: `assault 意为「攻击，袭击」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_188',
    type: 'vocabulary',
    prompt: `选择与「适用的，合适的」对应的英文单词：`,
    options: ["boom","bachelor","cuisine","applicable"],
    answer: 3,
    explanation: `applicable 意为「适用的，合适的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_189',
    type: 'vocabulary',
    prompt: `选择与「替代的，选择」对应的英文单词：`,
    options: ["combat","alternative","chill","colonial"],
    answer: 1,
    explanation: `alternative 意为「替代的，选择」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_190',
    type: 'vocabulary',
    prompt: `选择与「匿名的，无名的」对应的英文单词：`,
    options: ["charity","cargo","anonymous","commerce"],
    answer: 2,
    explanation: `anonymous 意为「匿名的，无名的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_191',
    type: 'vocabulary',
    prompt: `选择与「当代的，同时代的」对应的英文单词：`,
    options: ["classic","contemporary","civil","chamber"],
    answer: 1,
    explanation: `contemporary 意为「当代的，同时代的」。`,
    sourceEvent: '敌方消耗',
    difficulty: 3
  },
  {
    id: 'vocab_gen_192',
    type: 'vocabulary',
    prompt: `选择与「事先，预先」对应的英文单词：`,
    options: ["coarse","beforehand","charm","charity"],
    answer: 1,
    explanation: `beforehand 意为「事先，预先」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_193',
    type: 'vocabulary',
    prompt: `选择与「真正的，正宗的」对应的英文单词：`,
    options: ["cautious","authentic","coarse","adolescent"],
    answer: 1,
    explanation: `authentic 意为「真正的，正宗的」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_194',
    type: 'vocabulary',
    prompt: `选择与「保护，保存」对应的英文单词：`,
    options: ["conservation","compel","courtesy","crack"],
    answer: 0,
    explanation: `conservation 意为「保护，保存」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_195',
    type: 'vocabulary',
    prompt: `选择与「童年，幼年」对应的英文单词：`,
    options: ["convey","beforehand","childhood","condemn"],
    answer: 2,
    explanation: `childhood 意为「童年，幼年」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_196',
    type: 'vocabulary',
    prompt: `选择与「电路，环行」对应的英文单词：`,
    options: ["circuit","compact","comment","chop"],
    answer: 0,
    explanation: `circuit 意为「电路，环行」。`,
    sourceEvent: '对线补兵',
    difficulty: 2
  },
  {
    id: 'vocab_gen_197',
    type: 'vocabulary',
    prompt: `选择与「违反，突破」对应的英文单词：`,
    options: ["betray","cling","breach","campus"],
    answer: 2,
    explanation: `breach 意为「违反，突破」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
  {
    id: 'vocab_gen_198',
    type: 'vocabulary',
    prompt: `选择与「补偿，赔偿」对应的英文单词：`,
    options: ["compensate","beneath","category","captive"],
    answer: 0,
    explanation: `compensate 意为「补偿，赔偿」。`,
    sourceEvent: '1v1单杀',
    difficulty: 1
  },
  {
    id: 'vocab_gen_199',
    type: 'vocabulary',
    prompt: `选择与「方便，便利」对应的英文单词：`,
    options: ["bud","convenience","circulate","cluster"],
    answer: 1,
    explanation: `convenience 意为「方便，便利」。`,
    sourceEvent: '对线补兵',
    difficulty: 1
  },
  {
    id: 'vocab_gen_200',
    type: 'vocabulary',
    prompt: `选择与「开花，繁盛」对应的英文单词：`,
    options: ["cuisine","bronze","bloom","cape"],
    answer: 2,
    explanation: `bloom 意为「开花，繁盛」。`,
    sourceEvent: '敌方消耗',
    difficulty: 1
  },
];
